version: '3.8'

services:
  mysql_service:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: integrador_2
      MYSQL_USER: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql:rw

  phpmyadmin_service:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_service
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8081:80"
    depends_on:
      - mysql_service

volumes:
  db_data: